### ISSUE TITLE
Support for 24CSx parts

### ISSUE THREAD

**Issue by kiranshila** [eldruin/eeprom24x-rs#15]
Hey, thanks for the great library! Quick question - is there support yet for the 24CSx parts (the ones with baked in unique IDs)? I'm working specifically with the `AT24CSW010`. If not, would you be interested in a PR?

**Comment by eldruin** [comment]
Hi. There is no support for those parts yet. I would indeed be glad for a PR adding support for them.
This could be done by adding a new marker type to `Eeprom24x`, so that additional CS-series-specific methods are available only when using such device. This spares everybody else of matching errors that can never happen due to the chip choice.
Then you will need to tweak the creation macros to add a method like `new_24csw01` or similar.
I would not bother adding support for the `x` in `AT24CSW01x` since that can already be achieved through the `SlaveAddr` type.
